src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::resource('users', Onyx\User\UserController::class);
Route::post('ajaxDeleteUser', 'Onyx\User\UserController@ajaxDeleteUser');
Route::post('ajaxGetUserRole', 'Onyx\User\UserController@ajaxGetUserRole');

Route::prefix('api')->group(function () {

    // display all users
    Route::get('user', [Onyx\User\Api\UserController::class, 'index']);

    // insert new users
    Route::post('user/create', [Onyx\User\Api\UserController::class, 'insert']);

    // display specific users by userId
    Route::get('user/{userId}', [Onyx\User\Api\UserController::class, 'get']);

    // update specific user by userId
    Route::put('user/{userId}', [Onyx\User\Api\UserController::class, 'update']);

    // delete specific user by userId
    Route::delete('user/{userId}', [Onyx\User\Api\UserController::class, 'delete']);
});

src/resources/views/create.blade.php
@section('page_title')
    {{ $pageTitle .' |' }}
@endsection
<x-base-layout>
    @if(\Illuminate\Support\Facades\Auth::user()->role->user_create == 0)
        <div class="card d-flex justify-content-center" style="width: 100%;height: 100%;">
            <div style="margin: 0 auto;" class="d-flex flex-column justify-content-center">
                <img src="{{ asset(theme()->getMediaUrlPath() . 'logos/logo.png') }}" width="300" alt="" style="margin: auto !important;">
                <h2 class="fw-boldest text-gray-700 mt-5">Nemáte oprávnění k zobrazení této strany!</h2>
            </div>
        </div>
    @else

    @if (count($errors) > 0)
    <!--begin::Alert-->
        <div class="alert alert-danger">
            <!--begin::Wrapper-->
            <div class="d-flex flex-column">
                <!--begin::Title-->
                <h4 class="mb-1 text-danger mb-5">Něco nám tu chybí</h4>
                <!--end::Title-->
                <!--begin::Content-->
                <ul>
                    @foreach ($errors->all() as $error)
                        <li class="text-danger">{{ $error }}</li>
                    @endforeach
                </ul>
                <!--end::Content-->
            </div>
            <!--end::Wrapper-->
        </div>
        <!--end::Alert-->
    @endif
    <form method="POST" class="form" action="{{ route('users.store') }}" enctype="multipart/form-data" >
        @csrf
        <div class="card shadow">

            <div class="card-header d-flex justify-content-between py-5 px-5">
                <a href="{{ route('users.index') }}" class="btn btn-secondary font-weight-bolder shadow-sm">
                    <i class="fa fa-arrow-circle-left"></i> zpět
                </a>
                <div class="mt-4"><h2 class="text-gray-700">Nový uživatel</h2></div>
                <button type="submit" class="btn btn-primary font-weight-bolder shadow-sm btn-hover-scale" name="submitForm" id="submitForm">
                    <i class="fa fa-save fw-boldest" id="btnSave"></i>
                    <i class="fa fa-check d-none fw-boldest" id="btnSaveCheck"></i>
                    Uložit
                </button>
            </div>

            <div class="card-body px-0">
                <div class="tab-content pt-5">
                    <div class="tab-pane active" id="kt_apps_contacts_view_tab_2" role="tabpanel">
                        <div class="form-group row">
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Jméno</label>
                                <div class="col-lg-6">
                                    <input type="text" name="first_name" class="form-control form-control-solid" value="{{ old('first_name') }}" placeholder="Zadejte křestní jméno">
                                    @error('first_name')
                                    <span class="text-danger">Vyplňte prosím jméno</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Příjmení</label>
                                <div class="col-lg-6">
                                    <input type="text" name="last_name" class="form-control form-control-solid" value="{{ old('last_name') }}" placeholder="Zadejte příjmení">
                                    @error('last_name')
                                    <span class="text-danger">Vyplňte prosím přijmení</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700" style="text-align: right;">Titul před</label>
                                <div class="col-lg-6">
                                    <input type="text" name="title_before" class="form-control form-control-solid" value="{{ old('title_before') }}" placeholder="Zadejte titul před jménem">
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700" style="text-align: right;">Titul za</label>
                                <div class="col-lg-6">
                                    <input type="text" name="title_after" class="form-control form-control-solid" value="{{ old('title_after') }}" placeholder="Zadejte titul za jménem">
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Role</label>
                                <div class="col-lg-6">
                                    <select class="form-control form-select form-select-solid" name="role_id" id="role_id">
                                        <option value="" disabled selected>Vyberte roli</option>
                                        @foreach($roles as $role)
                                            <option {{ $role->id === old('role_id') ? "selected" : "" }} value="{{ $role->id }}">
                                                {{ $role->name_cs }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">E-mail</label>
                                <div class="col-lg-6">
                                    <input type="email" name="email" class="form-control form-control-solid" value="{{ old('email') }}"  placeholder="Zadejte email" autocomplete="off">
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Heslo</label>
                                <div class="col-lg-6">
                                    <!--begin::Main wrapper-->
                                    <div class="fv-row" data-kt-password-meter="true">
                                        <!--begin::Wrapper-->
                                        <div class="mb-1">
                                            <!--begin::Input wrapper-->
                                            <div class="position-relative mb-3">
                                                <input class="form-control form-control-lg form-control-solid"
                                                       type="password" placeholder="Zadejte heslo" name="password" autocomplete="off" value=""/>
                                                <!--begin::Visibility toggle-->
                                                <span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2"
                                                      data-kt-password-meter-control="visibility">
                                                <i class="bi bi-eye-slash fs-2"></i>

                                                <i class="bi bi-eye fs-2 d-none"></i>
                                            </span>
                                                <!--end::Visibility toggle-->
                                            </div>
                                            <!--end::Input wrapper-->
                                            <!--begin::Highlight meter-->
                                            <div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
                                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
                                            </div>
                                            <!--end::Highlight meter-->
                                        </div>
                                        <!--end::Wrapper-->

                                        <!--begin::Hint-->
                                        <div class="text-muted">
                                            Heslo musí být minimálně 8 znaků dlouhé a musí obsahovat minimálně jednu číslici a speciální znak
                                        </div>
                                        <!--end::Hint-->
                                    </div>
                                    <!--end::Main wrapper-->
                                    @error('password')
                                    <span class="text-danger">Vyplňte prosím heslo</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Telefon</label>
                                <div class="col-lg-6">
                                    <input type="text" name="phone" class="form-control form-control-solid" id="phone" value="{{ old('phone') }}" placeholder="Zadejte telefonní číslo">
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Aktivní</label>
                                <div class="col-lg-6">
                                    <div class="form-check form-switch form-check-custom form-check-solid">
                                        <input name="active" class="form-check-input" type="checkbox" id="flexSwitchChecked" {{ old("active") ? "checked" : "" }} />
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700" style="text-align: right;">Poznámka</label>
                                <div class="col-lg-6">
                                    <textarea id="form7" class="md-textarea form-control form-control-solid" rows="3" name="note" placeholder="Zadejte poznámku k uživateli">{{ old('note') }}</textarea>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    @endif
</x-base-layout>

<script>

    $('#submitForm').mouseenter(function () {

        $('#btnSave').addClass('d-none');
        $('#btnSaveCheck').removeClass('d-none');

    });

    $('#submitForm').mouseleave(function () {

        $('#btnSave').removeClass('d-none');
        $('#btnSaveCheck').addClass('d-none');

    });

    if (@json(old("role_id"))){

        $("#role_id").val(@json(old("role_id")));
    }

    Inputmask({
        "mask" : "999 999 999"
    }).mask("#phone");

</script>

src/resources/views/edit.blade.php
@section('page_title')
    {{ $pageTitle .' |' }}
@endsection
<x-base-layout>

    @if(\Illuminate\Support\Facades\Auth::user()->role->user_edit == 0)
        <div class="card d-flex justify-content-center" style="width: 100%;height: 100%;">
            <div style="margin: 0 auto;" class="d-flex flex-column justify-content-center">
                <img src="{{ asset(theme()->getMediaUrlPath() . 'logos/logo.png') }}" width="300" alt="" style="margin: auto !important;">
                <h2 class="fw-boldest text-gray-700 mt-5">Nemáte oprávnění k zobrazení této strany!</h2>
            </div>
        </div>
    @else

    @if (count($errors) > 0)
    <!--begin::Alert-->
        <div class="alert alert-danger">
            <!--begin::Wrapper-->
            <div class="d-flex flex-column">
                <!--begin::Title-->
                <h4 class="mb-1 text-danger mb-5">Něco nám tu chybí</h4>
                <!--end::Title-->
                <!--begin::Content-->
                <ul>
                    @foreach ($errors->all() as $error)
                        <li class="text-danger">{{ $error }}</li>
                    @endforeach
                </ul>
                <!--end::Content-->
            </div>
            <!--end::Wrapper-->
        </div>
        <!--end::Alert-->
    @endif

    <form method="POST" class="form" action="{{ route('users.update', $user) }}" enctype="multipart/form-data" >
        @csrf
        @method('PUT')
        <div class="card shadow">

            <div class="card-header d-flex justify-content-between py-5 px-5">
                <a href="{{ route('users.index') }}" class="btn btn-secondary font-weight-bolder shadow-sm">
                    <i class="fa fa-arrow-circle-left"></i> zpět
                </a>
                <div class="mt-4"><h2 class="text-gray-700">Editace uživatele {{ $user->getFullName() }}</h2></div>
                <button type="submit" class="btn btn-primary font-weight-bolder shadow-sm btn-hover-scale" name="submitForm" id="submitForm">
                    <i class="fa fa-save fw-boldest" id="btnSave"></i>
                    <i class="fa fa-check d-none fw-boldest" id="btnSaveCheck"></i>
                    Uložit
                </button>
            </div>

            <div class="card-body px-0">
                <div class="tab-content pt-5">
                    <div class="tab-pane active" id="kt_apps_contacts_view_tab_2" role="tabpanel">
                        <div class="form-group row">
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Jméno</label>
                                <div class="col-lg-6">
                                    <input type="text" name="first_name" class="form-control form-control-solid" value="{{ old('first_name', $user->first_name) }}" placeholder="Zadejte křestní jméno">
                                    @error('first_name')
                                    <span class="text-danger">Vyplňte prosím jméno</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Příjmení</label>
                                <div class="col-lg-6">
                                    <input type="text" name="last_name" class="form-control form-control-solid" value="{{ old('last_name', $user->last_name) }}" placeholder="Zadejte příjmení">
                                    @error('last_name')
                                    <span class="text-danger">Vyplňte prosím přijmení</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700" style="text-align: right;">Titul před</label>
                                <div class="col-lg-6">
                                    <input type="text" name="title_before" class="form-control form-control-solid" value="{{ old('title_before', $user->title_before) }}" placeholder="Zadejte titul před jménem">
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700" style="text-align: right;">Titul za</label>
                                <div class="col-lg-6">
                                    <input type="text" name="title_after" class="form-control form-control-solid" value="{{ old('title_after', $user->title_after) }}" placeholder="Zadejte titul za jménem">
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Role</label>
                                <div class="col-lg-6">
                                    <select class="form-control form-select form-select-solid" name="role_id" id="role_id">
                                        <option value="" disabled selected>Vyberte roli</option>
                                        @foreach($roles as $role)
                                            <option {{ $role->id === old('role_id') ? "selected" : "" }} value="{{ $role->id }}">
                                                {{ $role->name_cs }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">E-mail</label>
                                <div class="col-lg-6">
                                    <input type="email" name="email" class="form-control form-control-solid" value="{{ old('email', $user->email) }}"  placeholder="Zadejte email" autocomplete="off">
                                </div>
                                @error('email')
                                <span class="text-danger">Vyplňte prosím email</span>
                                @enderror
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Heslo</label>
                                <div class="col-lg-6">
                                    <!--begin::Main wrapper-->
                                    <div class="fv-row" data-kt-password-meter="true">
                                        <!--begin::Wrapper-->
                                        <div class="mb-1">
                                            <!--begin::Input wrapper-->
                                            <div class="position-relative mb-3">
                                                <input class="form-control form-control-lg form-control-solid"
                                                       type="password" placeholder="Zadejte heslo" name="password" autocomplete="off" value=""/>
                                                <!--begin::Visibility toggle-->
                                                <span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2"
                                                      data-kt-password-meter-control="visibility">
                                                <i class="bi bi-eye-slash fs-2"></i>

                                                <i class="bi bi-eye fs-2 d-none"></i>
                                            </span>
                                                <!--end::Visibility toggle-->
                                            </div>
                                            <!--end::Input wrapper-->
                                            <!--begin::Highlight meter-->
                                            <div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
                                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
                                            </div>
                                            <!--end::Highlight meter-->
                                        </div>
                                        <!--end::Wrapper-->

                                        <!--begin::Hint-->
                                        <div class="text-muted">
                                            Heslo musí být minimálně 8 znaků dlouhé a musí obsahovat minimálně jednu číslici a speciální znak
                                        </div>
                                        <!--end::Hint-->
                                        <div class="separator my-2"></div>
                                        <!--begin::Hint-->
                                        <div class="text-muted">
                                            Jestli si nepřejete měnit stávající heslo, ponechte pole prázdné
                                        </div>
                                        <!--end::Hint-->
                                    </div>
                                    <!--end::Main wrapper-->
                                    @error('password')
                                    <span class="text-danger">Vyplňte prosím heslo</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Telefon</label>
                                <div class="col-lg-6">
                                    <input type="text" name="phone" class="form-control form-control-solid" id="phone" value="{{ old('phone', $user->phone) }}" placeholder="Zadejte telefonní číslo">
                                    @error('phone')
                                    <span class="text-danger">Vyplňte prosím telefon</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700 required" style="text-align: right;">Aktivní</label>
                                <div class="col-lg-6">
                                    <div class="form-check form-switch form-check-custom form-check-solid">
                                        <input name="active" class="form-check-input" type="checkbox" id="flexSwitchChecked" {{ old("active", $user->active) ? "checked" : "" }} />
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row mb-10">
                                <label class="col-lg-3 col-form-label fw-boldest text-gray-700" style="text-align: right;">Poznámka</label>
                                <div class="col-lg-6">
                                    <textarea id="form7" class="md-textarea form-control form-control-solid" rows="3" name="note" placeholder="Zadejte poznámku k uživateli">{{ old('note', $user->note) }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </form>

    @endif

</x-base-layout>

<script>

    $('#submitForm').mouseenter(function () {

        $('#btnSave').addClass('d-none');
        $('#btnSaveCheck').removeClass('d-none');

    });

    $('#submitForm').mouseleave(function () {

        $('#btnSave').removeClass('d-none');
        $('#btnSaveCheck').addClass('d-none');

    });

    if (@json(old("role_id", $user->role_id))){

        $("#role_id").val(@json(old("role_id", $user->role_id)));
    }

    Inputmask({
        "mask" : "999 999 999"
    }).mask("#phone");

</script>

src/resources/views/partials/index.blade.php
<div class="card shadow">
    <div class="card-header border-0 pt-5">
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label fw-bolder fs-3 mb-1">Naposledy přidaní uživatelé</span>
        </h3>
        <div class="card-toolbar">
            @if(\Illuminate\Support\Facades\Auth::user()->role->user_create)
                <a href="{{ route('users.create') }}" class="btn btn-sm btn-light-primary me-2">
                    <i class="fa fa-plus-circle"></i> Nový uživatel
                </a>
                <a href="{{ route('users.index') }}" class="btn btn-sm btn-primary float-right fw-bolder">
                    <i class="bi bi-person"></i> Všichni uživatelé
                </a>
            @endif
        </div>
    </div>

    <div class="separator my-5"></div>

    <div class="card-body py-3">
        <div class="table-responsive">
            <table class="table table-row-dashed table-row-gray-300 align-middle gs-0 gy-4">
                <thead>
                <tr class="fw-bolder text-muted">
                    <th class="min-w-130px">Jméno</th>
                    <th class="min-w-130px">Příjmení</th>
                    <th class="min-w-130px">Role</th>
                    <th class="min-w-130px">E-mail</th>
                    <th class="min-w-130px"></th>
                </tr>
                </thead>

                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>
                            <div class="d-flex flex-column w-100 me-2">
                                <div class="d-flex flex-stack mb-2">
                                        <span class="text-muted me-2 fs-7 fw-boldest text-gray-700">
                                            {{ $user->first_name }}
                                        </span>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="d-flex flex-column w-100 me-2">
                                <div class="d-flex flex-stack mb-2">
                                        <span class="text-muted me-2 fs-7 fw-boldest text-gray-700">
                                            {{ $user->last_name }}
                                        </span>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="d-flex flex-column w-100 me-2">
                                <div class="d-flex flex-stack mb-2">
                                        <span class="me-2 fs-7 fw-bold">
                                            <span class="badge {{ $user->role->id == 1 ? "badge-light-danger" : "badge-light-primary"}}">{{ $user->role->name_cs }}</span>
                                        </span>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="d-flex flex-column w-100 me-2">
                                <div class="d-flex flex-stack mb-2">
                                        <span class="text-muted me-2 fs-7 fw-bold">
                                            {{ $user->email }}
                                        </span>
                                </div>
                            </div>
                        </td>
                        <td class="text-end">
                            @if(\Illuminate\Support\Facades\Auth::user()->role->user_edit)
                                <a href="{{ route('users.edit',$user->id) }}" class="btn btn-icon btn-bg-light btn-active-color-info btn-sm me-1">
                                    <span class="svg-icon svg-icon-3">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                        <path opacity="0.3" d="M21.4 8.35303L19.241 10.511L13.485 4.755L15.643 2.59595C16.0248 2.21423 16.5426 1.99988 17.0825 1.99988C17.6224 1.99988 18.1402 2.21423 18.522 2.59595L21.4 5.474C21.7817 5.85581 21.9962 6.37355 21.9962 6.91345C21.9962 7.45335 21.7817 7.97122 21.4 8.35303ZM3.68699 21.932L9.88699 19.865L4.13099 14.109L2.06399 20.309C1.98815 20.5354 1.97703 20.7787 2.03189 21.0111C2.08674 21.2436 2.2054 21.4561 2.37449 21.6248C2.54359 21.7934 2.75641 21.9115 2.989 21.9658C3.22158 22.0201 3.4647 22.0084 3.69099 21.932H3.68699Z" fill="black"></path>
                                        <path d="M5.574 21.3L3.692 21.928C3.46591 22.0032 3.22334 22.0141 2.99144 21.9594C2.75954 21.9046 2.54744 21.7864 2.3789 21.6179C2.21036 21.4495 2.09202 21.2375 2.03711 21.0056C1.9822 20.7737 1.99289 20.5312 2.06799 20.3051L2.696 18.422L5.574 21.3ZM4.13499 14.105L9.891 19.861L19.245 10.507L13.489 4.75098L4.13499 14.105Z" fill="black"></path>
                                        </svg>
                                    </span>
                                </a>
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>